// VREFBUF
pub const VREFBUF = struct {
    // VREFBUF control and status register
    CSR: packed struct(u32) {
        // Voltage reference buffer mode enable
        // This bit is used to enable the voltage reference
        // buffer mode.
        ENVR: u1,
        // High impedance mode This bit controls
        // the analog switch to connect or not the VREF+ pin.
        // Refer to Table196: VREF buffer modes for the mode
        // descriptions depending on ENVR bit
        // configuration.
        HIZ: u1,
        // Reserved
        _reserved_2: u1,
        // Voltage reference buffer ready
        VRR: u1,
        // Voltage reference scale These bits
        // select the value generated by the voltage reference
        // buffer. Other: Reserved
        VRS: u3,
        // Reserved
        _reserved_7: u25,
    },
    // VREFBUF calibration control register
    CCR: packed struct(u32) {
        // Trimming code These bits are
        // automatically initialized after reset with the
        // trimming value stored in the Flash memory during the
        // production test. Writing into these bits allows to
        // tune the internal reference buffer
        // voltage.
        TRIM: u6,
        // Reserved
        _reserved_6: u26,
    },
};

pub const VREFBUF_BASE_ADDRESS: usize = 0x58003C00;
pub const VREFBUF_REGISTERS: *volatile VREFBUF = @ptrFromInt(VREFBUF_BASE_ADDRESS);
